**思考**：
- 什么是第三方库？Python与第三方库的关系？
- 为什么要用numpy？

库的**导入**方法：
- `import numpy`
- `import numpy as np`
- `from numpy import array`

# 数组的创建
- `array()`
- `arange()`
- `zeros()`
- `ones()`

In [2]:
import numpy as np

In [3]:
vector = np.array([5,10,15,20]) #一维数组
matrix = np.array([[5,10,15,20],[20,25,30,35],[35,40,45,50]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15 20]
 [20 25 30 35]
 [35 40 45 50]]


In [4]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
Zerosvector = np.zeros([4,3],np.int)
Onesvector = np.ones([4,3],np.float)
print(Zerosvector)
print(Onesvector)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 数组的形状
- `shape`

In [6]:
print(vector.shape)  #(4,)
print(matrix.shape) #(3,4)

(4,)
(3, 4)


In [7]:
matrix.shape = 4 ,3
print(matrix.shape)

(4, 3)


In [8]:
matrix.shape = -1 ,6
print(matrix.shape)

(2, 6)


# 存取元素

In [10]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(a[5])
print(a[3:5])
print(a[:5])
print(a[:-1]) 

5
[3 4]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8]


In [12]:
a[2:4] = 100, 101
a

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

![](./npcunqu.png)

# 数组计算

## 加、减、乘、除、开方

In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x,y

(array([[1., 2.],
        [3., 4.]]), array([[5., 6.],
        [7., 8.]]))

In [14]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


## 矩阵相乘（`np.dot()`）

In [15]:
np.dot(x,y)

array([[19., 22.],
       [43., 50.]])

## 计算数组中所有元素之和(`np.sum()`)

In [16]:
np.sum(x)

10.0

## 转置矩阵

In [17]:
np.dot(x,y).T

array([[19., 43.],
       [22., 50.]])

# 广播机制

![](./broadcast.png)

In [18]:
a = np.array([0,10,20,30]).reshape(4,1)
b = np.array([0,1,2]).reshape(1,3)
print(a,b)

[[ 0]
 [10]
 [20]
 [30]] [[0 1 2]]


In [19]:
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
